src/Acr.UserDialogs.Android/UserDialogsImpl.cs

On Android 4.4 JellyBean with ```PromptConfig.InputType = InputType.Email``` the keyboard didn't show **@** character. Changing ```txt.InputType = InputTypes.TextVariationEmailAddress;``` to ```txt.InputType = InputTypes.ClassText | InputTypes.TextVariationEmailAddress;``` seems to work. 
Didn't test if the problem persists on other devices/versions.
[http://developer.android.com/reference/android/widget/TextView.html#attr_android:inputType](http://developer.android.com/reference/android/widget/TextView.html#attr_android:inputType) textview inputType of textEmailAddress corresponds to the above fix.

Android: InputTypes.ClassText | InputTypes.TextVariationEmailAddress for Email case

---

src/Acr.UserDialogs.iOS/UserDialogsImpl.cs

This makes the search for the top view controller recursive so when you have a modal stack over one the dialog appear correctly.

Fix for #28

---

src/Acr.UserDialogs.iOS/UserDialogsImpl.cs

Contains the following changes:
- show OK action on the right and cancel on the left
- change appearance of cancel button to UIAlertActionStyle.Cancel
This follows the [iOS Human Interface Guidelines](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Alerts.html#//apple_ref/doc/uid/TP40006556-CH14-SW1):
> When the most likely button performs a nondestructive action, it should be on the right in a two-button alert. The button that cancels this action should be on the left.

Change order of cancel and OK buttons in iOS prompt

---

src/Acr.UserDialogs.Android.AppCompat/Acr.UserDialogs.Android.AppCompat.csproj

Manually updated the reference to the incorrect v7 project. Xamarin Studio didn't pick up that mistake.

Small fix for the incorrect reference to v7 AppCompact

---

src/Acr.UserDialogs.iOS/UserDialogsImpl.cs

Apple's iOS Human Interface Guidelines suggest placing destructive actions at the top.
https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Alerts.html

Add destructive action sheet button first

---

src/Acr.UserDialogs.Uwp/ProgressContentDialog.xaml

It is little but annoying visual problem, ProgressContentDialog.xaml has MinHeight value as 184. Therefore, if anyone call the showloading function with simple text it appears like this,
http://prntscr.com/buf7ai
with this change,
http://prntscr.com/buf8cw

UWP ProgressContentDialog height issue fix

---

src/Acr.UserDialogs.iOS/UserDialogsImpl.cs

iOS TimePicker did not use SelectedTime property when creating the picker, but defaulted to the current time

fix #239 - iOS TimePicker not using SelectedTime

---

src/Acr.UserDialogs.Uwp/UserDialogsImpl.cs

Minor cosmetic fix--for whatever reason, the TextBlock used to display the message in a Prompt defaults to a TextWrapping value of NoWrap.
Also, I noticed that in the UWP project, you have a PromptDialog control, but the code doesn't actually use it. Is that an artifact from a previous design, or something you're intending to use in the future? I.E. should I adjust this PR to work with the PromptDialog control?

Fix Prompt message text not wrapping in UWP

---

src/Acr.UserDialogs.Interface/AbstractUserDialogs.cs
src/Samples/Samples/ViewModels/SpecificCasesViewModel.cs

This PR adds proper cleanup of CancellationTokenRegistations by wrapping `CancellationToken.Register()` into a using.
1. checkout `415c7bb` and add a breakpoint at Android UserDialogsImpl.cs:344
2. compile and tap on new example (Specific cases -> Two alerts with one Cancellation Token Source)
3. tap Ok
4. wait until second dialog gets dismissed
5. count breakpoint hits (you will count 2 hits,but it should only be one, because the first dialog has been closed)
6. checkout `5b42c4d`
7. do 2-5. (you will count 1 hit)
Because of the missing deregistration, you could end up with some memory leaks because of the captured closure in all `CancellationToken.Register()`.
see: [MSDN: How to: Register Callbacks for Cancellation Requests](https://msdn.microsoft.com/en-us/library/ee191554(v=vs.110).asp …

CancelationToken registration fix

---

src/Acr.UserDialogs.iOS/TTGSnackbar.cs

This will fix #348 and make toast height to expand if a text message longer than 2 lines is set.

#348 make toast height dynamic to expand if needed

---

src/Acr.UserDialogs/Acr.UserDialogs.csproj

There's a bug in the project file that `UserDialogs` is not included to compile for UWP target framework. Lack of compiling this file results in missing of `UserDialogs.Instance`  in the DLL and UWP APP crashes.
this pull request fixes this problem.

fix UWP project bug

---

src/Acr.UserDialogs/Platforms/Android/ProgressDialog.cs

1) Also send the activity to AndHUD when dismissing so that it has a fallback option to dismiss the dialog.
2) Remove the UI thread invoker around the Show method. AndHUD has fixed that in its own code and not having the showing and the dismissing following the same threading logic, causes race conditions.
Threading in AndHUD: https://github.com/Redth/AndHUD/blob/master/AndHUD/AndHUD.cs#L298 
This has fixed an issue I was experiencing when using  AcrDialogs in an async method.

Fixed threading issue with AndHUD

---

src/Acr.UserDialogs/Acr.UserDialogs.csproj

Had to ditch the old MonoAndroid70 and MonoAndroid80 targets. They are not
supported in the Play Store anyways.
Fixes #582

Update to AndHUD 1.4.1

---

src/Acr.UserDialogs/Platforms/Uwp/UserDialogsImpl.cs

Fix for the issue #334,  based on this solution https://stackoverflow.com/a/19051399/3546760 with some refactoring.
Tried to subscribe to the event like this:
```
popup.LayoutUpdated += Popup_LayoutUpdated;
```
but the sender was null so I ended up passing the sender manually
```
popup.LayoutUpdated += (sender, e) =>
{
Popup_LayoutUpdated(popup, e);
};
```
I guess it's a bug in UWP, so until it fixed we should use this workaround. I also wrote a TODO in the code explaining the issue and that it should be changed when they fix the bug.
Tested only on Windows 10, version 10.0.17763.0

[UWP] Date and Time dialogs aren't centered #334

---

src/Acr.UserDialogs/Platforms/Uwp/UserDialogsImpl.cs

Message and Icon is not in the same line 
change text wrapping to fix this

change text wrapping in uwp

---

readme.md

The MvvmCross API has changed, `Mvx.Resolve` is deprecated. `Mvx.IoCProvider.Resolve` should be used instead.

Readme: Updated MvvmCross initalization example code

---

src/Acr.UserDialogs/Platforms/Android/Builders/PromptBuilder.cs

When specifying the InputType.DecimalNumber as the input to the prompt dialog.
Fixes #263

Add NegativeSign to list of acceptable input characters

---

src/Acr.UserDialogs/Platforms/Android/Builders/ActionSheetListAdapter.cs
src/Acr.UserDialogs/Platforms/Android/Extensions.cs
src/Acr.UserDialogs/Platforms/Android/Fragments/BottomSheetDialogFragment.cs

Rows in an sheet alert or bottomsheet didn't have a ripple/pressed state. This is annoying for the user because it can't see visual feedback.
None
None
- Android
Rows now have a ripple effect

Add a ripple effect to rows when being pressed

---

src/Acr.UserDialogs/Platforms/Android/Fragments/ConfigStore.cs

Changing `ConfigStore.Contains(Bundle)` to check for presence of the config key in its local dictionary instead of only checking whether the bundle contains the config store key.
I wanted to keep this a oneliner, and I just realized that makes the code look a bit hacky. I'll expand it into a method body if that suits you better.
- fixes #637 
None
None
- Android
None
Follow the testing procedure in #637 and verify there is no crash. I'm currently short on time and have trouble building on my Mac but I'll test myself later if required.

Adding a fix for #637

---

src/Acr.UserDialogs/Platforms/ios/AIDatePickerController.cs

Fix for issue #673
I changed background color for AIDatePickerController from UIColor.White new value is UIColor.TertiarySystemBackgroundColor which using system color for Light and Dark mode. This change is only for IOS platform.
- fixes #673
None
- iOS
None

DatePrompt and TimePrompt does not display properly on iOS 13 (#673)

---

src/Acr.UserDialogs/Platforms/Android/Builders/LoginBuilder.cs

I think issue #400 can be fixed by changing of InputType on username field. `TextVariationVisiblePassword` is intended for password and not username. I guess `ClassText` would be better.
- fixes #400 
None
- Android
None

Change InputType in Android LoginBuilder; fixes #400

---

src/Acr.UserDialogs/Platforms/ios/AIDatePickerController.cs

use black text when in dark mode, tertiary color becomes white which fades into white background (this technically does not add support for dark mode, but only fixes a bug with disappearing text)
addresses #699 but does not fully resolve it
None
- iOS
None
The date picker should be tested on iOS >= v13 in dark mode.

fix invisible text iOS 13 dark mode date picker

---

src/Samples/Samples/ViewModels/ToastsViewModel.cs

- fixes a bug in the sample app, using Toasts, for when the user activates ShowOnTop switch, it can't turn it off
None
- iOS
- Android
None (sample only)
1. Open the app
2. Navigate to Toasts tab
3. Click Show On Top
4. Click it again
The app should let user to turn this switch off

Fixed ShowOnTop using Toasts Sample

---

src/Acr.UserDialogs/Platforms/ios/AIDatePickerController.cs

fe9d16d86928e9ec5e0bf856cea3ce833932deb8 fixed crashes with iOS<13 but #718 regressed these changes, resulting in a crash when opening the date picker on iOS<13 because `UIColor.TertiarySystemBackgroundColor` is not available on iOS<12. This attempts to resolve that crash, applies some additional checks that should help with iOS<12 (`UIUserInterfaceStyle.Dark` isn't available on iOS<12), and applies the same `UIUserInterfaceStyle.Dark` checks for tvOS.
- Addresses a regression with a previous fix to #699 but doesn't address the issue beyond that.
None
- iOS
Will set date picker background color to black on iOS12 if `this.TraitCollection.UserInterfaceStyle == UIUserInterfaceStyle.Dark` when the date picker is created.
Test that date picker works on iOS<12, iOS12, iOS13 and tvOS, with dark …

Fix crash on iOS 12 and make color selection consistent on tvOS

---

src/Acr.UserDialogs/Platforms/ios/AIDatePickerController.cs

Before this PR, the dark mode setting was respected but only when showing the view controller. Changes to the setting while the controller was visible where not respected.
None
- iOS
None
See video.

Datepicker on iOS: Update colors when prompt is open and dark mode is turned on/off

---

src/Acr.UserDialogs/Platforms/ios/AIDatePickerController.cs

Added null check for previousTraitCollection in AIDatePickerController's TraitCollectionDidChange method.
- fixes #753 - Time and Date dialogs crash in iOS <= 12
None
- iOS
None
Run Samples.iOS project on simulator running iOS <= 12 and test Date and Time prompts

#753 - Time and Date dialogs crash in iOS <= 12

---

src/Acr.UserDialogs/Platforms/Android/Builders/PromptBuilder.cs

When using InputType.Password or InputType.NumericPassword in PromptConfig this change prevents Android to present suggestions based on earlier entries.
This could become critical when prompt dialog is used to request a password.
fixes #757 -> [Enhancement] Android - In PromptBuilder set "No suggestion"-Flag if InputType.Password
None
Android
When a prompt dialog is presented, with this change no suggestions based on earlier entries will be presented if InputType of PromptConfig is NumericPassword or Password.
Open a prompt dialog with InputType.Password or InputType.NumericPassword and enter "123456". Close dialog. Open same prompt dialog again. No suggestions by Android will be made.

#757 Android - In PromptBuilder set "No suggestion"-Flag if InputType.Password

---

src/Acr.UserDialogs/Acr.UserDialogs.csproj
src/Samples/Samples.Droid/Samples.Droid.csproj

attempt to fix #756 by changing the `DebugType` from `full` to `portable` for all platforms (reverts the change added in 6953dd1695fcb032011178fd2253751451c42f3b )
- fixes #756 
None
- Android
None
compile the app in Preview of VS2019 16.9 and the warning about deprecated debug symbol is gone

changed DebugType to portable

---

src/Acr.UserDialogs/DatePromptConfig.cs
src/Acr.UserDialogs/IiOSStyleDialogConfig.cs
src/Acr.UserDialogs/Platforms/ios/AIDatePickerController.cs
src/Acr.UserDialogs/Platforms/ios/UserDialogsImpl.cs
src/Acr.UserDialogs/TimePromptConfig.cs
src/Acr.UserDialogs/iOSPickerStyle.cs

I've exposed the dialog style selector for the iOS time picker
- fixes #768 
Added picker style properties to TimePickerConfig
Passed values to the Controller for use in the presentation code
- iOS
Allows the consuming application to show time dialogs in iOS 14 as wheel pickers.
Run the test iOS application and specify ```iOSPickerStyle = iOSPickerStyle.Wheels``` in the config options

Fix for issue #768

---

src/Acr.UserDialogs/Platforms/ios/UserDialogsImpl.cs

The destructive action sheet should be at the end of the action sheet options before the cancel operation.
This change aligns with Android and macOS behavior.

Move destructive action sheet after default ones

---

src/Acr.UserDialogs/AutoCorrectionConfig.cs
src/Acr.UserDialogs/Platforms/Android/Builders/PromptBuilder.cs
src/Acr.UserDialogs/Platforms/ios/UserDialogsImpl.cs
src/Acr.UserDialogs/PromptConfig.cs
src/Samples/Samples/ViewModels/StandardViewModel.cs

Implemented support for defining AutoCorrect behavior in prompts.
None
None
- iOS
- Android
The default AutoCorrectionConfig is .Default, which doesn't alter any behavior.
The sample app has been updated to have a Autocorrect Prompt and NoAutocorrect prompt option, which has been used during development.

Implemented AutoCorrect Configuration for Prompts

---

src/Acr.UserDialogs/Platforms/ios/AIDatePickerController.cs

AIDatePickerController will now use the formatted value instead of simple nfloat to string conversion.
If the device uses specific languages with number format (1.230,00), SafeAreaInsets.Bottom is a fraction value and causes an error.
None
- iOS
None
UIApplication.SharedApplication.KeyWindow.SafeAreaInsets needs to be a fraction value
- [x ] Rebased on top of the target branch at time of PR
- [x ] Changes adhere to coding standard

Fixed error with fraction values for specific languages in AIDatePickerController

---

src/Acr.UserDialogs/Acr.UserDialogs.csproj
src/Acr.UserDialogs/Platforms/ios/Extensions.cs
src/Acr.UserDialogs/Platforms/ios/ProgressDialog.cs

Update BTProgressHUD to v1.3.4 to fix iOS 15 crashes
- Fixes crashes on iOS 15 originated in the BTProgressHUD library. More info can be found on [Issue #84](https://github.com/redth-org/BTProgressHUD/issues/84)
None
- iOS
None
Test that the app doesn't crash on IOS 15. Most of my observed crashes were when the app was on background or doing background fetch.

Fix iOS 15 Crashes

---

src/Acr.UserDialogs/Platforms/Uwp/UserDialogsImpl.cs

This allows the user to press the Enter key to submit their values.
If the user is entering a value on the keyboard, it is natural to press the Enter key to finish the entry.
The ContentDialog.DefaultButton property was introduced in Windows 10, version 1703 (build 15063).
Acr.UserDialogs currently requires a minimum of build 16299.
None
None
- UWP
The Enter key will become functional, hopefully reducing end-user frustration.
I created a subclass of UserDialogsImpl and overrode the Prompt() method in my local UWP project and it worked well.  I am not currently setup to build the Acr.UserDialogs library.

Allow user to press Enter to submit value on UWP

---

src/Acr.UserDialogs/Platforms/Android/UserDialogsImpl.cs

The Show method above already build the dialog on the UI thread but the ShowDialog doesn't. Ensure that it is also the case for the ShowDialog method.
This modification fix the following exception reported in our production logs
> Java.Lang.IllegalStateException: Method addObserver must be called on the main thread
The complete stacktrace of the crash
```cs
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
at object System.Reflection.RuntimeConstructorInfo.InternalInvoke(object obj, object[] parameters, bool wrapExceptions)
at object RuntimeType.CreateInstanceMono(bool nonPublic, bool wrapExceptions)
at object RuntimeType.CreateInstanceSlow(bool publicOnly, bool wrapExceptions, bool skipCheckThis, bool fillCache)
at object …
```

Android - Build dialog fragment on UI thread

---

src/Acr.UserDialogs/Acr.UserDialogs.csproj
src/Acr.UserDialogs/Platforms/ios/Extensions.cs
src/Acr.UserDialogs/Platforms/ios/ProgressDialog.cs

This PR fixes incompatibility between Acr.UserDialogs and BTProgressHUD v1.3.5.
BTProgressHUD version 1.3.5 contains stability improvements for iOS 15. Unfortunately, due namespace changes, it will not work (compile) with the latest Acr.UserDialogs.
- More stability fixes for iOS 15: https://github.com/redth-org/BTProgressHUD/issues/84#issuecomment-953911685
None
- iOS
None

Use BTProgressHUD 1.3.5

---

src/Acr.UserDialogs/ConfirmConfig.cs

When using a `ConfirmDialog` without setting any arguments, its buttons default to `DefaultOkText` and `DefaultCancelText` and this behavior cannot be changed in anyway. So the only option *was* to always use `UseYesNo`. With these changes one can now set the property `DefaultUseYesNo` to `true` (`false` by default to ensure no changes in existing code) to have the `ConfirmDialog` buttons default to `DefaultYes` and `DefaultNo` instead.
None
A new static property `DefaultUseYesNo` was added (`false` by default to ensure no changes in existing code) that can be set to `true` to have the `ConfirmDialog` buttons default to `DefaultYes` and `DefaultNo` instead of  `DefaultOkText` and `DefaultCancelText`.
- All
None

Added DefaultUseYesNo to ConfirmConfig to switch between OK/Cancel and Yes/No globally

---

src/Acr.UserDialogs/AbstractUserDialogs.cs

In my last PR I sadly forgot to also let the `ConfirmAsync` overload without `ConfirmConfig` parameter make use of the new `DefaultUseYesNo` property. This PR changes that.
Fixes that using `ConfirmAsync` with and without `ConfirmConfig` parameter will result in different button texts when using `DefaultUseYesNo = true` and not setting `OkText` and/or `CancelText`.
None
- All
`ConfirmAsync` with and without `ConfirmConfig` parameter will now result in the same output (as originally intended), when using `DefaultUseYesNo = true` and not providing `OkText` and/or `CancelText`.

Updated ConfirmAsync so it uses new DefaultUseYesNo property as the ConfirmConfig overload does
